name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Install dev tools
        run: uv pip install isort black flake8 pytest scrapy

      - name: Check imports with isort
        run: isort . --check-only

      - name: Check style with black
        run: black . --check

      - name: Lint with flake8
        run: flake8 .

      - name: Test with pytest
        run: pytest || [ $? -eq 5 ]
